<?php
/*
 * NCLFMinecraft.org
 * Copyright (C) 2012  A.J. Fite
 */
class News_model extends CI_Model {
	
	public function __construct() {
		$this->load->database();
	}

	public function get_news($slug = FALSE,$limit = NULL) {
		if($slug === FALSE) {
			//Returns newest news first
			$this->db->order_by('date','desc');
			$query = $this->db->get('news');
			return $query->result_array();
		}
		
		if(!is_null($limit)) {
			$query = $this->db->get('news', $limit);
			return $query->row_array();
		}
	
		$query = $this->db->get_where('news', array('slug' => $slug));
		return $query->row_array();
	}
	
	public function set_news() {
		$this->load->helper('url');
		$this->load->library('email');
		
		$slug = url_title($this->input->post('title'), 'dash',TRUE);
		
		$data = array(
				'title' => $this->input->post('title'),
				'slug' => $slug,
				'text' => $this->input->post('text'),
				'author' => $this->input->post('author'));
		
		//Email mirror news in Facebook group

		return $this->db->insert('news',$data);
	}
	
	public function email_news() {
		$this->email->from('do-not-reply@nclf.net', 'NCLF DO NOT REPLY');
		$this->email->to('nclfminecraft@groups.facebook.com');
		$this->email->subject($data['title']);
		$this->email->message($data['text']."\r\n \r\nAutomatically generated by the NCLFMinecraft.org News Service\r\nPosted by ".$data['author']);
		
		return $this->email->send();
	}
	
}